### ISSUE TITLE
[13주차] 취약 유형 (DP, 이분탐색)

### ISSUE THREAD

**Issue by funnysunny08** [2023-Coding-Test-Study/Coding-Test-Study#65]
### 필수 문제 

`Level 3` [징검다리 건너기](https://school.programmers.co.kr/learn/courses/30/lessons/64062)
🥇 [두 용액](https://www.acmicpc.net/problem/2470)
🥈 [이항 계수2](https://www.acmicpc.net/problem/11051)
🥇 [LCS 2](https://www.acmicpc.net/problem/9252)
🥇 [1학년](https://www.acmicpc.net/problem/5557)

### 선택 문제 

https://stonejjun.tistory.com/24

### 같이 풀어볼 문제 

`Level 3` [징검다리 건너기](https://school.programmers.co.kr/learn/courses/30/lessons/64062)
🥇 [두 용액](https://www.acmicpc.net/problem/2470)
🥇 [LCS 2](https://www.acmicpc.net/problem/9252)

**Comment by juijeong8324** [comment]
앗싸라비야 콜롬비야 좋은 문제덜 감사합니다
